apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::864974731196:role/eksctl-eksctl-demo-nodegroup-ng-e-NodeInstanceRole-1GCIZF8ZZA3RI
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::864974731196:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-30T12:49:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1614"
  uid: 6c83a05f-d053-432c-9ccf-34aba2095268
